#!/bin/bash
tar -cf $TAR_ARCHIVE_FILE $SOURCE_ARCHIVE_DIR
zstd -$ZSTD_COMPRESSION_LEVEL $TAR_ARCHIVE_FILE -o $COMPRESSED_ARCHIVE_FILE
echo "UNCOMPRESSED_SIZE=$(stat --printf='%s' $TAR_ARCHIVE_FILE)" >> $GITHUB_ENV